### ISSUE TITLE
create phantom with meep package [SOLVED]

### ISSUE THREAD

**Issue by ReDoDx09** [sp00ks-L/Meep-Simulations#1]
Hi,
I saw your meep simulations project and it's very interesting, i would like to do the same but this time i would like to work on another sample (for your it was bacteria) for my case it will be material with different components each component has its own refractive index until now i didn't find a good tutorial for that. please do you have some documents about this stuff or website in order to do this?
Thank you

**Comment by sp00ks-L** [comment]
It has been a while so Meep may have changed since I was using it but I think it will depend on how complex the shape/material is that you're trying to model. For me, my model was just a small circle within a second larger circle, each having their own refractive index. 

Not sure if you're using the Python interface or not but if you can model your material using Meep's GeometricObjects - https://meep.readthedocs.io/en/latest/Python_User_Interface/#geometricobject - you can then perhaps assemble a collection of these objects into your desired material. You then just assign each shape with it's own properties - https://meep.readthedocs.io/en/latest/Python_User_Interface/#medium - each can have its own refractive index etc.  If you have already tried this then I am not entirely sure.

**Comment by ReDoDx09** [comment]
Thank you for your answer and your help.
Yes, I'm using Python interface and I want to create Sheep Logan phantom and do Computed tomography with it.
Do you have some real pictures of your created object? this way I can understand your codes, also did you write a report about your work (i can give you my mail) 
thank's again

**Comment by sp00ks-L** [comment]
Apologies for the late reply, I have attached an image of 2 figures from the dissertation I wrote accompanying my code. The first is a simplistic diagram to explain what I was trying to achieve and then the second is an actual output from one of my simulations. 
![Meep Diss Figures](https://user-images.githubusercontent.com/55932367/118395760-fab28680-b643-11eb-9249-c46f1f89f856.png)

I also found this paper which may be of more use to you because they use Meep for simulation and reconstruction of the phantom - you may well have seen this already.  I do have a report with a bit more detail on my simulations that I can send you but it is obviously about their applications to the bacteria that I was modelling. 

Feng, T. (2020). Time of arrival imaging: The proof of concept for a novel medical imaging modality. arXiv: Image and Video Processing.
[Feng-2020.pdf](https://github.com/sp00ks-L/Meep-Simulations/files/6489141/Feng-2020.pdf)

**Comment by ReDoDx09** [comment]
Hello again,
thank you a lot for your clarification.
since your code is available on GitHub it would be better to see your report as well to better understand your work
here is my email (enpo.automatique@gmail.com), please send me your report when you have time.
Thank you.
